apps/home/urls.py
from django.conf.urls import url
from django.urls import path, include

from .views import IndexView, DetailView, AuspiciadoresView, WorkShopsView, CharlasView


urlpatterns = [
    path('', IndexView.as_view(),name='index'),
    path('auspiciadores', AuspiciadoresView.as_view(),name='auspiciadores'),
    path('workshops', WorkShopsView.as_view(),name='workshops'),
    path('charlas', CharlasView.as_view(),name='charlas'),
]

pyday/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include

from django.conf import settings

from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls import handler404


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('apps.home.urls','home'),namespace='home')),
    path('', include(('apps.speaker.urls','speakers'),namespace='speakers')),
    path('', include(('apps.inscription.urls','inscription'),namespace='inscription')),
]

handler404 = 'apps.home.views.error_404_view'

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/partials/banner.html
<div class="overlay-black">
    <div class="container">
        <div class="banner-main-design">
            <div class="row full-screen align-items-center">
                <div class="col-lg-12 col-md-12">
                    <div class="banner-left text-center">
                        <h1>Pyladies La Paz</h1>
                        <p class="cd-headline clip is-full-width mt-15">
                            <span>PyDay </span>
                            <span class="cd-words-wrapper">
                                <b class="is-visible">Charlas</b>
                                <b>WorkShops</b> 
                                <b>Talleres</b>
                                <b>Proyectos</b>
                                <b>Comunidades.</b>
                            </span>
                        </p>
        
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

templates/partials/css.html
    {% load staticfiles %}

    <link rel="stylesheet"  href="{% static 'css/fontawesome-all.css' %}">
    <link rel="stylesheet"  href="{% static 'bootstrap/css/bootstrap.css' %}">
    <link rel="stylesheet"  href="{% static 'css/owl.carousel.min.css' %}">
    <link rel="stylesheet"  href="{% static 'css/owl.theme.default.min.css' %}">
    <link rel="stylesheet"  href="{% static 'css/magnific-popup.css' %}">
    <link rel="stylesheet"  href="{% static 'css/animate.min.css' %}">
    <link rel="stylesheet"  href="{% static 'css/progresscircle.css' %}">
    <link href="https://fonts.googleapis.com/css?family=Lato:300,400,700,900" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Raleway:200,300,400,500,600,700,800,900%7cOpen+Sans:400,600,700,800" rel="stylesheet">

    <link rel="stylesheet" type="text/css" href="{% static 'css/cubeportfolio.min.css' %}">
    <link rel="stylesheet"  href="{% static 'css/style.css' %}">
    <link rel="stylesheet"  href="{% static 'css/page.css' %}">
    <link rel="stylesheet"  href="{% static 'css/blog.css' %}">
    <link id="colors" rel="stylesheet" href="{% static 'css/black-color.css' %}">

templates/partials/footer.html
<div class="container">
    <div class="row">
         <div class="col-lg-12">
             <div class="copy-right">
                 <p> &copy; {% now 'Y' %}. PyLadies La Paz </p>
             </div>
         </div>
    </div>
</div>

templates/partials/js.html
    {% load staticfiles %}
    <script src="{% static 'js/jquery-3.0.0.min.js' %}"></script>
    <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/jquery.stellar.js' %}"></script>
    <script src="{% static 'js/animated.headline.js' %}"></script>
    <script src="{% static 'js/owl.carousel.min.js' %}"></script>
    <script src="{% static 'js/scrollIt.min.js' %}"></script>
    <script src="{% static 'js/isotope.pkgd.min.js' %}"></script>
    <script src="{% static 'js/jquery.magnific-popup.min.js' %}"></script>
    <script src="{% static 'js/progresscircle.js' %}"></script>
    <script  src="{% static 'js/jquery.cubeportfolio.min.js' %}"></script>
    <script src="{% static 'js/main.js' %}"></script>

templates/partials/navbar.html
    <ul class="navbar-nav ml-auto">
        <li class="nav-item">
            <a href="#" class="nav-link active" data-scroll-nav="0" >Inicio</a>
        </li>
        <li class="nav-item">
            <a href="#" class="nav-link" data-scroll-nav="1" >Pyladies</a>
        </li>
        <li class="nav-item">
            <a href="#" class="nav-link" data-scroll-nav="2" >Actividades</a>
        </li>
        <li class="nav-item">
            <a href="#" class="nav-link" data-scroll-nav="3">Speakers</a>
        </li>
        <li class="nav-item">
            <a href="#" class="nav-link" data-scroll-nav="4">Cronograma</a>
        </li>
        <li class="nav-item">
            <a href="#" class="nav-link" data-scroll-nav="5">Charlas</a>
        </li>
        <li class="nav-item">
            <a href="#" class="nav-link" data-scroll-nav="6">Contactos</a>
        </li>
        <li class="nav-item">
            <a href="#" class="nav-link" data-scroll-nav="7">Auspiciadores</a>
        </li>
    </ul>

templates/partials/navbarlink.html
<ul class="navbar-nav ml-auto">
    <li class="nav-item">
        <a href="{% url 'home:index' %}" class="nav-link active">Inicio</a>
    </li>
    <li class="nav-item">
        <a href="https://www.meetup.com/es-ES/La-Paz-PyLadies-Meetup/" target="_blank" class="nav-link">Pyladies</a>
    </li>
    <li class="nav-item">
        <a href="{% url 'home:workshops' %}" class="nav-link">Actividades</a>
    </li>
    <li class="nav-item">
        <a href="{% url 'home:charlas' %}" class="nav-link">Speakers</a>
    </li>
    <li class="nav-item">
        <a href="{{ url_cronograma }}" class="nav-link">Cronograma</a>
    </li>
    <li class="nav-item">
        <a href="{% url 'home:charlas' %}" class="nav-link">Charlas</a>
    </li>
    <li class="nav-item">
        <a href="https://www.meetup.com/es-ES/La-Paz-PyLadies-Meetup/" target="_blank" class="nav-link">Contactos</a>
    </li>
    <li class="nav-item">
        <a href="{% url 'home:auspiciadores' %}" class="nav-link">Auspiciadores</a>
    </li>
</ul>