apps/home/urls.py
from django.conf.urls import url
from django.urls import path, include

from .views import IndexView, DetailView, AuspiciadoresView, WorkShopsView, CharlasView


urlpatterns = [
    path('', IndexView.as_view(),name='index'),
    path('auspiciadores', AuspiciadoresView.as_view(),name='auspiciadores'),
    path('workshops', WorkShopsView.as_view(),name='workshops'),
    path('charlas', CharlasView.as_view(),name='charlas'),
]

apps/inscription/urls.py
from django.urls import path
from django.conf.urls import url

from .views import FormInscriptionView, MessageSuccessFormView
from . import views


urlpatterns = [
    path('formulario_inscripcion', FormInscriptionView.as_view(),name='formulario'),
    path('ajax/load-cities/', views.load_tematic, name='ajax_load_tematic'),
    path('registro_exitoso', MessageSuccessFormView.as_view(), name='registro'),
]

pyday/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include

from django.conf import settings

from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls import handler404


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('apps.home.urls','home'),namespace='home')),
    path('', include(('apps.speaker.urls','speakers'),namespace='speakers')),
    path('', include(('apps.inscription.urls','inscription'),namespace='inscription')),
]

handler404 = 'apps.home.views.error_404_view'

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/inscription/models.py
from django.db import models

class Tipo(models.Model):

    name = models.CharField(
        max_length=150,
        verbose_name = "Charla o Taller --> Categoria"
    )
    
    def __str__(self):
        return self.name


class TipoInscripcion(models.Model):

    inscripcion = models.ForeignKey(
        Tipo, on_delete=models.CASCADE
    )
    
    name = models.CharField(
        max_length = 150,
        verbose_name = "El nombre de la Charla o Taller"
    )

    quota = models.IntegerField(
        verbose_name = "Cupo"
    )

    def __str__(self):
        return self.name



VARON = 'V'
MUJER = 'M'
OTRO = 'O'

AGE_CHOICES = [
    ('M', 'Mujer'),
    ('V', 'Varon'),
    ('O', 'Otro'),
]


class Inscrito(models.Model):

    name = models.CharField(
        max_length=100,
        verbose_name = "Nombre completo del participante"
    )

    email = models.EmailField(
        verbose_name = "Correo"
    )

    phone = models.IntegerField(
        verbose_name = "Número de Celular"
    )

    age = models.IntegerField(
        verbose_name = "Edad",
        blank = True,
        null = True
    )

    gender = models.CharField(
        max_length = 4,
        choices = AGE_CHOICES,
        default = VARON,
        verbose_name = "Género"
    )

    institution = models.CharField(
        max_length = 200,
        verbose_name = "Institución Educativa/ Empresa/Otros"
    )

    level = models.CharField(
        max_length = 200,
        verbose_name = "Nivel/Año que cursa (Colegio/Universidad)",
        blank = True,
        null = True
    )

    tipo = models.ForeignKey(
        Tipo, on_delete = models.SET_NULL, 
        null = True,
        blank = True,
        verbose_name = "Tipo"
    )

    tipoinscripcion = models.ForeignKey(
        TipoInscripcion, on_delete=models.SET_NULL,
        null = True,
        blank = True,
        verbose_name = "Categoria"
    )

    def __str__(self):
        return "%s /  %s " %(self.name,self.tipo)

apps/inscription/forms.py
from django import forms
from .models import Inscrito, TipoInscripcion


class PersonForm(forms.ModelForm):
    class Meta:

        model = Inscrito

        fields = (
            'name',
            'email',
            'phone',
            'age',
            'gender',
            'institution',
            'level',
            'tipo',
            'tipoinscripcion'
        )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['tipoinscripcion'].queryset = TipoInscripcion.objects.none()

        if 'tipo' in self.data:
            try:
                tipo_id = int(self.data.get('tipo'))

                self.fields['tipoinscripcion'].queryset = TipoInscripcion.objects.filter(inscripcion_id=tipo_id).order_by('name')
            except (ValueError, TypeError):
                pass
        elif self.instance.pk:
            self.fields['tipoinscripcion'].queryset = self.instance.tipo.tipoinscripcion_set.order_by('name')

apps/inscription/views.py
from django.shortcuts import render
from django.views.generic import ListView, CreateView, UpdateView
from django.views.generic.base import TemplateView

from django.urls import reverse_lazy

from .models import Inscrito, TipoInscripcion
from .forms import PersonForm
from constance import config


class FormInscriptionView(CreateView):
    
    model = Inscrito
    form_class = PersonForm
    success_url = reverse_lazy('inscription:registro')

    
    
def load_tematic(request):
    
    tipo_id = request.GET.get('tipo')
    tematics = TipoInscripcion.objects.filter(inscripcion_id=tipo_id).order_by('name')

    return render(request, 'inscription/list_options.html', {'tematics': tematics})


class MessageSuccessFormView(TemplateView):
    
    template_name = 'inscription/message_registration.html'
    
    def get_context_data(self, **kwargs):
        context = super(MessageSuccessFormView, self).get_context_data(**kwargs)
        context['message_form'] = config.MESSAGE_FORM
        return context

templates/inscription/inscrito_form.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% load staticfiles %}

{% block extracss %}
    <style>
        #form {
        background-color: #F9F9F9;
        }

        .blue {
        color: #2CAFFD;
        }

        #inputDado {
        border-radius: 30px;
        border: 1px solid #000;
        }
    </style>
{% endblock extracss %}

{% block content %}

<nav class="navbar navbar-expand-lg navbar-dark">
    <div class="container">
  
        <a class="navbar-brand logo">
            <img src="{% static 'images/logo_pyladies.png' %}">
        </a>
  
        <button class="navbar-toggler collapsed" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
  
        <div class="navbar-collapse collapse" id="navbarCollapse">
            {% include 'partials/navbarlink.html' %}
        </div>
    </div>
  </nav>

<section class="page-title"
    style="background-image: url('{% static 'images/banner/py_image.png' %}');background-attachment: fixed; background-repeat: no-repeat; background-size: cover;background-position: center;"
    data-stellar-background-ratio=".7" data-scroll-index="0">
    <div class="overlay">
        <div class="container">
            <div class="page-title-div">
                <h1>
                    PyDay
                </h1>
            </div>
        </div>
    </div>
</section>

<section class="pt-100 pb-100 blog-details-post" data-scroll-index="5">
    <div class="container">
        <div class="row">
            <div class="col-md-9">

            <div>
                <div class="col">
                    <div class="section-title">
                        <div class="main-title">
                            <div class="title-main-page">
                                <h4>Formulario de Inscripción</h4>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
                    
            <div class="post-content">
                <div class="entry-body">
                    <form method="post" id="personForm" data-tematics-url="{% url 'inscription:ajax_load_tematic' %}" novalidate>
                        {% csrf_token %}
                        <table>
                            {{ form|crispy }}
                        </table>

                        <div class="cloundcontainer">
                        </div>
                        
                        <button type="submit" class="btn btn-primary">Registrarme</button>

                    </form>
                        
                    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
                    <script>
                        $("#id_tipo").change(function () {
                            var url = $("#personForm").attr("data-tematics-url");
                            var countryId = $(this).val();

                            $.ajax({
                                url: url,
                                data: {
                                    'tipo': countryId
                                },
                                success: function (data) {
                                    $("#id_tipoinscripcion").html(data);
                                    $('.cloundcontainer').empty()
                                    $('.cloundcontainer').append('<div class="cloud"><blockquote>- Con la inscripción usted podra acceder a todas las charlas, asi tambien si gusta puede inscribirse a un taller</blockquote></div>')
                                }
                            });
                    
                        });
                    </script>
                </div>

            </div>
        </div>

    <div class="col-md-3">
      <div class="blog-sidebar">
            <div class="widget categories-widget">
                <h3>Facebook</h3>
                <div class="fb-page" data-href="https://www.facebook.com/pyladieslapaz/" data-tabs="timeline" data-width="700" data-height="700" data-small-header="false" data-adapt-container-width="true" data-hide-cover="false" data-show-facepile="true"><blockquote cite="https://www.facebook.com/Incoslapaz2019/" class="fb-xfbml-parse-ignore"><a href="https://www.facebook.com/Incoslapaz2019/">pyladieslapaz</a></blockquote></div>
            </div>
      </div>
    </div>
    
    </div>
    </div>
</section>


{% endblock content %}

{% block extrajs %}

<div id="fb-root"></div>
<script async defer crossorigin="anonymous" src="https://connect.facebook.net/es_LA/sdk.js#xfbml=1&version=v3.3&appId=383264375339567&autoLogAppEvents=1"></script>


{% endblock extrajs %}

templates/inscription/list_options.html
<option value="">---------</option>
{% for tematic in tematics %}
<option value="{{ tematic.pk }}">{{ tematic.name }}</option>
{% endfor %}

templates/inscription/message_registration.html
{% extends 'base.html' %}

{% load staticfiles %}

{% block extracss %}

    <link rel="stylesheet" href="{% static 'css/project.css' %}">

{% endblock extracss %}

{% block content %}

<nav class="navbar navbar-expand-lg navbar-dark">
    <div class="container">
  
        <a class="navbar-brand logo">
            <img src="{% static 'images/logo_pyladies.png' %}">
        </a>
  
        <button class="navbar-toggler collapsed" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
  
        <div class="navbar-collapse collapse" id="navbarCollapse">
            {% include 'partials/navbarlink.html' %}
        </div>
    </div>
  </nav>

<section class="page-title"
    style="background-image: url('{% static 'images/banner/py_image.png' %}');background-attachment: fixed; background-repeat: no-repeat; background-size: cover;background-position: center;" data-stellar-background-ratio=".7" data-scroll-index="0">
    <div class="overlay">
        <div class="container">
            <div class="page-title-div">
                <h1>
                    PyDay
                </h1>
            </div>
        </div>
    </div>
</section>

<section class="pt-100 pb-100">
    <div>
        <div class="col">
            <div class="section-title">
                <div class="main-title">
                    <div class="title-main-page">
                        <h4>Te registraste Exitosamente</h4>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="container">
        <div class="row">
            <blockquote>
                <p> 
                    {{ message_form }} 
                </p>
                <meta http-equiv="refresh" content="5;url={% url 'home:index' %}">
            </blockquote>
        </div>
    </div>
</section>
{% endblock content %}

{% block extrajs %}

{% endblock extrajs %}