apps/inscription/urls.py
from django.urls import path
from django.conf.urls import url

from .views import FormInscriptionView, MessageSuccessFormView
from . import views


urlpatterns = [
    path('formulario_inscripcion', FormInscriptionView.as_view(),name='formulario'),
    path('ajax/load-cities/', views.load_tematic, name='ajax_load_tematic'),
    path('registro_exitoso', MessageSuccessFormView.as_view(), name='registro'),
]

apps/speaker/urls.py
from django.urls import path
from django.conf.urls import url

from .views import DetailSpeakerView

urlpatterns = [
    url(r'^speaker-detail/(?P<slug>[\w-]+)/$', DetailSpeakerView.as_view(), name='speaker-detail'),
]

pyday/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include

from django.conf import settings

from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls import handler404


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('apps.home.urls','home'),namespace='home')),
    path('', include(('apps.speaker.urls','speakers'),namespace='speakers')),
    path('', include(('apps.inscription.urls','inscription'),namespace='inscription')),
]

handler404 = 'apps.home.views.error_404_view'

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/auspiciadores.html
{% extends 'base.html' %}

{% load staticfiles %}

{% block extracss %}

{% endblock extracss %}

{% block content %}

<nav class="navbar navbar-expand-lg navbar-dark">
  <div class="container">

      <a class="navbar-brand logo">
          <img src="{% static 'images/logo_pyladies.png' %}">
      </a>

      <button class="navbar-toggler collapsed" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
      </button>

      <div class="navbar-collapse collapse" id="navbarCollapse">
          {% include 'partials/navbarlink.html' %}
      </div>
  </div>
</nav>

<section class="page-title"
    style="background-image: url('{% static 'images/banner/py_image.png' %}');background-attachment: fixed; background-repeat: no-repeat; background-size: cover;background-position: center;"
    data-stellar-background-ratio=".7" data-scroll-index="0">
    <div class="overlay">
        <div class="container">
            <div class="page-title-div">
                <h1>
                    PyDay
                </h1>
            </div>
        </div>
    </div>
</section>


<br><br><br>

<div class="col">
    <div class="section-title">
        <div class="main-title">
            <div class="title-main-page">
                <h4>Auspiciadores / Comunidades</h4>
            </div>
        </div>
    </div>
</div>

<div class="container">
    <div class="row">
      <div class="col-md-4">

        <div class="card mb-5">
          <img class="card-img-top" src="{% static 'images/auspiciadores/01IMT-logotipo.png' %}"></img>
          <div class="card-body">
            <h5 class="card-title">Auspiciador</h5>
          </div>
        </div>

        <div class="card mb-5">
          <img class="card-img-top" src="{% static 'images/auspiciadores/elemental.png' %}"></img>
          <div class="card-body">
            <h5 class="card-title">Auspiciador</h5>
          </div>
        </div>

        
        <div class="card mb-5">
          <img class="card-img-top" src="{% static 'images/auspiciadores/ucb.jpg' %}"></img>
          <div class="card-body">
            <h5 class="card-title">Auspiciador</h5>
          </div>
        </div>
      </div>
      <div class="col-md-4">
        <div class="card mb-5">
          <img class="card-img-top" src="{% static 'images/auspiciadores/IMT-UCB-logo_Mesa.png' %}"></img>
          <div class="card-body">
            <h5 class="card-title">Auspiciador</h5>
          </div>
        </div>
        <div class="card mb-5">
          <img class="card-img-top" src="{% static 'images/auspiciadores/CloudLP.png' %}"></img>
          <div class="card-body">
            <h5 class="card-title">Auspiciador</h5>
          </div>
        </div>
      </div>
      <div class="col-md-4">

        <div class="card mb-5">
          <img class="card-img-top" src="{% static 'images/auspiciadores/pyladies_comunidad.png' %}"></img>
          <div class="card-body">
            <h5 class="card-title">Comunidad</h5>
          </div>
        </div>

        <div class="card mb-5">
          <img class="card-img-top" src="{% static 'images/auspiciadores/Simplificado_blank.png' %}"></img>
          <div class="card-body">
            <h5 class="card-title">Comunidad</h5>
          </div>
        </div>

      </div>
    </div>
</div>


{% endblock content %}

{% block extrajs %}

{% endblock extrajs %}

templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="zxx">
<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta name="keywords" content="Django Girls, Python, Talleres,La Paz Bolivia, Python La Paz, PyDay, PyDay La Paz, Pyladies La Paz">
    <meta name="description" content="PyDay organizado por la comunidad Pyladies La Paz , Pyladies La Paz">
    <meta name="author" content="@alfredynho, Alfredo Callizaya Gutierrez">
    <meta name="theme-color" content="#FFFFFF">
    <title>Pyladies - Pyday</title>

    <link rel="shortcut icon" href="{% static 'images/favicon.png' %}" />

    {% include 'partials/css.html' %}

    {% block extracss %}
        <!-- Block extracss -->
    {% endblock extracss %}
</head>
<body>

        {% block content %}

        {% endblock content %}

        <footer>
            {% include 'partials/footer.html' %}
        </footer>

    {% include 'partials/js.html' %}

    {% block extrajs %}
        <!-- Block extrajs -->
    {% endblock extrajs %}
</body>
</html>

templates/charlas.html
{% extends 'base.html' %}

{% load staticfiles %}

{% block extracss %}

{% endblock extracss %}

{% block content %}

<nav class="navbar navbar-expand-lg navbar-dark">
    <div class="container">

        <a class="navbar-brand logo">
            <img src="{% static 'images/logo_pyladies.png' %}">
        </a>

        <button class="navbar-toggler collapsed" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="navbar-collapse collapse" id="navbarCollapse">
            {% include 'partials/navbarlink.html' %}
        </div>
    </div>
</nav>

<section  class="page-title" style="background-image: url('{% static 'images/banner/py_image.png' %}');background-attachment: fixed; background-repeat: no-repeat; background-size: cover;background-position: center;" data-stellar-background-ratio=".7" data-scroll-index="0">
    <div class="overlay">
        <div class="container">
            <div class="page-title-div">
                <h1>PyDay - Pyladies</h1>
            </div>
        </div>
    </div>
</section>

<section  class="blog-grid-views pt-100 pb-100">
    
    <div class="col">
        <div class="section-title">
            <div class="main-title">
                <div class="title-main-page">
                    <h4>Charlas</h4>
                </div>
            </div>
        </div>
    </div>

    <div class="container">
        <div class="row">

            {% for sp in charlas %}

            <div class="col-lg-4 col-md-6">
                <div class="blog-post-wrapper-div">
                    <div>
                        <div class="blog-post-image-div">
                            <div class="clearfix">
                                <div class="img">
                                    <img src="{{ sp.photo.url }}" alt="image" class="img-responsive center-block"> 
                                </div>
                            </div>
                        </div>
                        <div class="post-detail-container-div">
                            <div class="post-content-div">
                                <h3 class="post-title entry-title">
                                <a href="{% url 'speakers:speaker-detail' sp.slug %}">{{ sp.topic }}</a>
                                </h3>
                                <ul class="list-unstyled list-inline post-metadata">
                                <li>
                                    <i class="fas fa-bookmark"></i> {{ sp.first_name }} {{ sp.last_name }} </li>
                                <li>
                                </ul>
                                <p class="post-excerpt"> {{ sp.description_of_the_topic }} </p>
                                <div class="view_detail">
                                <a href="{% url 'speakers:speaker-detail' sp.slug %}" class="blog-btn">Ver mas ...</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        {% endfor %}

        </div>
    </div>
</section>
    
{% endblock content %}

{% block extrajs %}

{% endblock extrajs %}

templates/detail.html
{% extends 'base.html' %}

{% load staticfiles %}

{% block extracss %}

    <link rel="stylesheet" href="{% static 'css/project.css' %}">

{% endblock extracss %}

{% block content %}

<nav class="navbar navbar-expand-lg navbar-dark">
    <div class="container">

        <a class="navbar-brand logo">
            <img src="{% static 'images/logo_pyladies.png' %}">
        </a>

        <button class="navbar-toggler collapsed" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="navbar-collapse collapse" id="navbarCollapse">
            {% include 'partials/navbarlink.html' %}
        </div>
    </div>
</nav>


<section class="page-title"
    style="background-image: url('{% static 'images/banner/py_image.png' %}');background-attachment: fixed; background-repeat: no-repeat; background-size: cover;background-position: center;"
    data-stellar-background-ratio=".7" data-scroll-index="0">
    <div class="overlay">
        <div class="container">
            <div class="page-title-div">
                <h1>
                    PyDay
                </h1>
            </div>
        </div>
    </div>
</section>

<section class="pt-100 pb-100">
    <div>
        <div class="col">
            <div class="section-title">
                <div class="main-title">
                    <div class="title-main-page">
                        <h4>{{ speaker.topic }}</h4>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="container">
        <div class="row">
            <div class="col-md-6">
                <div class="project-img">
                    <img src="{{ speaker.photo.url }}" alt="">
                </div>
            </div>
            <div class="col-md-6">
                <div class="project-details-title">
                    <h6> {{ speaker.institution }}</h6>
                    <h4>{{ speaker.first_name }} {{ speaker.last_name }}</h4>
                </div>
                <div class="project-details-table">
                    <table>
                        <tbody>
                            <tr>
                                <td><span>Nivel</span></td>
                                <td>{{ speaker.level }}</td>
                            </tr>
                            <tr>
                                <td><span>Horario</span></td>
                                <td>{{ speaker.exhibition_time }}</td>
                            </tr>
                            <tr>
                                <td><span>Area</span></td>
                                <td>{{ speaker.area }}</td>
                            </tr>
                            <tr>
                                <td><span>Tipo</span></td>
                                {% if speaker.is_workshop == True %}
                                    <td>Workshop</td>
                                {% else %}
                                    <td>Charla</td>
                                {% endif %}
                            </tr>
                        </tbody>
                    </table>
                </div>
                <div class="project-details-title">
                    <h5>Descripción</h5>
                </div>
                <div class="project-features">
                    <div class="row">
                        <div class="col-md-15" align="justify">
                            <p>{{ speaker.description_of_the_topic }}</p>
                        </div>

                        <div class="contact-social about-contact">
                            <ul>
                                <li class="social-text">Redes Sociales:</li>
                                
                                <li><a href="{{ speaker.social_facebook }}" target="_blank"><i class="fab fa-facebook-f"></i></a> </li>
                                <li><a href="{{ speaker.social_linkedin }}" target="_blank"><i class="fab fa-linkedin-in"></i>
                                <li><a href="{{ speaker.social_twitter }}" target="_blank"><i class="fab fa-twitter" target="_blank"></i></a></li>
                                <li><a href="https://www.meetup.com/es-ES/La-Paz-PyLadies-Meetup" target="_blank"><i class="fab fa-meetup"></i></a></li>
                            </ul>
                        </div>

                        <div class="col-md-6">

                        <div>
                            <a href="{% url 'inscription:formulario' %}" class="blog-btn">Inscribirme</a>
                        </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-12">
                <div class="project-description">
                    <p>
                        {{ speaker.biography }}
                    </p><br>
                    <div id="disqus_thread"></div>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock content %}

{% block extrajs %}

<script>
    (function () {
        var d = document,
            s = d.createElement('script');
        s.src = 'https://pyladies-la-paz.disqus.com/embed.js';
        s.setAttribute('data-timestamp', +new Date());
        (d.head || d.body).appendChild(s);
    })();
</script>

{% endblock extrajs %}

templates/error_404.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Pyladies</title>

    <link href="https://fonts.googleapis.com/css?family=Fredoka+One" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Raleway:400,700" rel="stylesheet">

    <style>
        * {
        -webkit-box-sizing: border-box;
        box-sizing: border-box;
        }

        body {
        padding: 0;
        margin: 0;
        }

        #notfound {
        position: relative;
        height: 100vh;
        }

        #notfound .notfound {
        position: absolute;
        left: 50%;
        top: 50%;
        -webkit-transform: translate(-50%, -50%);
        -ms-transform: translate(-50%, -50%);
        transform: translate(-50%, -50%);
        }

        .notfound {
        max-width: 710px;
        width: 100%;
        text-align: center;
        padding: 0px 15px;
        line-height: 1.4;
        }

        .notfound .notfound-404 {
        height: 200px;
        line-height: 200px;
        }

        .notfound .notfound-404 h1 {
        font-family: 'Fredoka One', cursive;
        font-size: 168px;
        margin: 0px;
        color: #ff508e;
        text-transform: uppercase;
        }

        .notfound h2 {
        font-family: 'Raleway', sans-serif;
        font-size: 22px;
        font-weight: 400;
        text-transform: uppercase;
        color: #222;
        margin: 0;
        }

        .notfound-search {
        position: relative;
        padding-right: 123px;
        max-width: 420px;
        width: 100%;
        margin: 30px auto 22px;
        }

        .notfound-search input {
        font-family: 'Raleway', sans-serif;
        width: 100%;
        height: 40px;
        padding: 3px 15px;
        color: #222;
        font-size: 18px;
        background: #f8fafb;
        border: 1px solid rgba(34, 34, 34, 0.2);
        border-radius: 3px;
        }

        .notfound-search button {
        font-family: 'Raleway', sans-serif;
        position: absolute;
        right: 0px;
        top: 0px;
        width: 120px;
        height: 40px;
        text-align: center;
        border: none;
        background: #ff508e;
        cursor: pointer;
        padding: 0;
        color: #fff;
        font-weight: 700;
        font-size: 18px;
        border-radius: 3px;
        }

        .notfound a {
        font-family: 'Raleway', sans-serif;
        display: inline-block;
        font-weight: 700;
        border-radius: 15px;
        text-decoration: none;
        color: #39b1cb;
        }

        .notfound a>.arrow {
        position: relative;
        top: -2px;
        border: solid #39b1cb;
        border-width: 0 3px 3px 0;
        display: inline-block;
        padding: 3px;
        -webkit-transform: rotate(135deg);
        -ms-transform: rotate(135deg);
        transform: rotate(135deg);
        }

        @media only screen and (max-width: 767px) {
        .notfound .notfound-404 {
        height: 122px;
        line-height: 122px;
        }
        .notfound .notfound-404 h1 {
        font-size: 122px;
        }
        }

    </style>
</head>

<body>

    <div id="notfound">
        <div class="notfound">
            <div class="notfound-404">
                <h1>404</h1>
            </div>
            <h2>¡OOPS, LA PÁGINA QUE ESTÁS BUSCANDO NO SE PUEDE ENCONTRAR!</h2>
            <a href="/"><span class="arrow"></span>Regresar a la página principal</a>
        </div>
    </div>

</body>

</html>

templates/workshops.html
{% extends 'base.html' %}

{% load staticfiles %}

{% block extracss %}

{% endblock extracss %}

{% block content %}

<nav class="navbar navbar-expand-lg navbar-dark">
    <div class="container">

        <a class="navbar-brand logo">
            <img src="{% static 'images/logo_pyladies.png' %}">
        </a>

        <button class="navbar-toggler collapsed" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="navbar-collapse collapse" id="navbarCollapse">
            {% include 'partials/navbarlink.html' %}
        </div>
    </div>
</nav>


<section  class="page-title" style="background-image: url('{% static 'images/banner/py_image.png' %}');background-attachment: fixed; background-repeat: no-repeat; background-size: cover;background-position: center;" data-stellar-background-ratio=".7" data-scroll-index="0">
    <div class="overlay">
        <div class="container">
            <div class="page-title-div">
                <h1>PyDay - Pyladies</h1>
            </div>
        </div>
    </div>
</section>

<section  class="blog-grid-views pt-100 pb-100">
    
    <div class="col">
        <div class="section-title">
            <div class="main-title">
                <div class="title-main-page">
                    <h4>Workshops</h4>
                </div>
            </div>
        </div>
    </div>

    <div class="container">
        <div class="row">

            {% for sp in workshop %}

            <div class="col-lg-4 col-md-6">
                <div class="blog-post-wrapper-div">
                    <div>
                        <div class="blog-post-image-div">
                            <div class="clearfix">
                                <div class="img">
                                    <img src="{{ sp.photo.url }}" alt="image" class="img-responsive center-block"> 
                                </div>
                            </div>
                        </div>
                        <div class="post-detail-container-div">
                            <div class="post-content-div">
                                <h3 class="post-title entry-title">
                                <a href="{% url 'speakers:speaker-detail' sp.slug %}">{{ sp.topic }}</a>
                                </h3>
                                <ul class="list-unstyled list-inline post-metadata">
                                <li>
                                    <i class="fas fa-bookmark"></i> {{ sp.first_name }} {{ sp.last_name }} </li>
                                <li>
                                </ul>
                                <p class="post-excerpt"> {{ sp.description_of_the_topic }} </p>
                                <div class="view_detail">
                                <a href="{% url 'speakers:speaker-detail' sp.slug %}" class="blog-btn">Ver mas ...</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        {% endfor %}

        </div>
    </div>
</section>
    
{% endblock content %}

{% block extrajs %}

{% endblock extrajs %}